version: '3'

services:
  node:
    image: node:10
    command: tail -F /dev/null
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5000:5000"
      - "5001:5001"
